{\rtf1\ansi\ansicpg1252\cocoartf1265\cocoasubrtf190
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs24 \cf0 CC = gcc\
#Using -Ofast instead of -O3 might result in faster code, but is supported only by newer GCC versions\
CFLAGS = -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result\
\
all: word2vec word2phrase distance word-analogy compute-accuracy\
\
word2vec : word2vec.c\
	$(CC) word2vec.c -o word2vec $(CFLAGS)\
word2phrase : word2phrase.c\
	$(CC) word2phrase.c -o word2phrase $(CFLAGS)\
distance : distance.c\
	$(CC) distance.c -o distance $(CFLAGS)\
word-analogy : word-analogy.c\
	$(CC) word-analogy.c -o word-analogy $(CFLAGS)\
compute-accuracy : compute-accuracy.c\
	$(CC) compute-accuracy.c -o compute-accuracy $(CFLAGS)\
	chmod +x *.sh\
\
clean:\
	rm -rf word2vec word2phrase distance word-analogy compute-accuracy\
}